# ---------- BUILD STAGE ----------
FROM maven:3.9.3-eclipse-temurin-17 AS build
WORKDIR /app

# Copy parent POM
COPY services/auth/pom.xml ./pom.xml

# Copy auth-service module
COPY services/auth/auth-service ./auth-service

# Build only auth-service module
RUN mvn -pl auth-service -am clean package -DskipTests

# ---------- RUNTIME ----------
FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /app/auth-service/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
