# azure-pipeline-terraform.yml
trigger:
  branches:
    include:
      - main

variables:
  ENVIRONMENT: 'dev'             # dev/prod, can override in pipeline
  ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
  ARM_TENANT_ID: $(ARM_TENANT_ID)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  TF_BACKEND_RG: '<backend-rg-name>'
  TF_BACKEND_STORAGE: '<backend-storage-name>'
  TF_BACKEND_CONTAINER: '<backend-container-name>'
  TF_VERSION: '1.14.3'

stages:

# Stage 1: Terraform Init
- stage: Terraform_Init
  displayName: "Terraform Init"
  jobs:
  - job: Init
    pool:
      name: 'azureagent'
    steps:
    - task: TerraformCLI@2
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'terraform/environments/$(ENVIRONMENT)'
        backendType: 'azurerm'
        backendServiceArm: '$(AZURE_SUBSCRIPTION)'
        ensureBackend: true
        backendAzureRmResourceGroupName: $(TF_BACKEND_RG)
        backendAzureRmStorageAccountName: $(TF_BACKEND_STORAGE)
        backendAzureRmContainerName: $(TF_BACKEND_CONTAINER)
        backendAzureRmKey: '$(ENVIRONMENT).tfstate'
        environmentServiceNameAzureRM: '$(AZURE_SUBSCRIPTION)'

# Stage 2: Terraform Validate
- stage: Terraform_Validate
  displayName: "Terraform Validate"
  dependsOn: Terraform_Init
  jobs:
  - job: Validate
    pool:
      name: 'azureagent'
    steps:
    - task: TerraformCLI@2
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: 'terraform/environments/$(ENVIRONMENT)'

# Stage 3: Terraform Plan
- stage: Terraform_Plan
  displayName: "Terraform Plan"
  dependsOn: Terraform_Validate
  jobs:
  - job: Plan
    pool:
      name: 'azureagent'
    steps:
    - task: TerraformCLI@2
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'terraform/environments/$(ENVIRONMENT)'
        environmentServiceNameAzureRM: '$(AZURE_SUBSCRIPTION)'
        commandOptions: '-var-file="$(ENVIRONMENT).tfvars" -out=tfplan'

# Stage 5: Manual Approval for Production
- stage: Terraform_Approval
  displayName: "Manual Approval"
  dependsOn: Terraform_Scan
  condition: eq(variables['ENVIRONMENT'], 'prod')
  jobs:
  - job: Approve
    pool:
      name: 'azureagent'
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: '<your-email@example.com>'
        instructions: 'Please approve Terraform apply for production.'

# Stage 6: Terraform Apply
- stage: Terraform_Apply
  displayName: "Terraform Apply"
  dependsOn: [Terraform_Plan, Terraform_Approval]
  jobs:
  - job: Apply
    pool:
      name: 'azureagent'
    steps:
    - task: TerraformCLI@2
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'terraform/environments/$(ENVIRONMENT)'
        environmentServiceNameAzureRM: '$(AZURE_SUBSCRIPTION)'
        commandOptions: '-auto-approve tfplan'
