trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - bank_application_ci/terraform/**

pool:
  name: azureagent

variables:
  TF_WORKING_DIR: $(System.DefaultWorkingDirectory)/terraform/environments/dev

stages:

# ===============================
# STAGE 1: INIT + VALIDATE
# ===============================
- stage: Validate
  jobs:
  - job: validate
    steps:

    - task: TerraformCLI@2
      displayName: Terraform Init
      inputs:
        command: 'init'
        workingDirectory: '$(TF_WORKING_DIR)'
        commandOptions: '-var subscription_id=$(subscription_id) -var tenant_id=$(tenant_id) -var client_id=$(client_id) -var client_secret=$(client_secret)'
        backendType: 'azurerm'
        backendServiceArm: 'payasyougo(c02db223-ae2a-4677-943f-e5864c5361a3)'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'tfstate-rg'
        backendAzureRmResourceGroupLocation: 'centralindia'
        backendAzureRmStorageAccountName: 'tfstatebankapp'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'
        allowTelemetryCollection: true
        

    - task: TerraformCLI@2
      displayName: Terraform Validate
      inputs:
        command: 'validate'
        workingDirectory: '$(TF_WORKING_DIR)'
        vars: |
          subscription_id=$(subscription_id)
          tenant_id=$(tenant_id)
          client_id=$(client_id)
          client_secret=$(client_secret)
        allowTelemetryCollection: true




# ===============================
# STAGE 2: PLAN
# ===============================
- stage: Plan
  dependsOn: Validate
  jobs:
  - job: plan
    workspace:
       clean: all 
    steps:

    - script: |
        rm -rf .terraform
        rm -f .terraform.lock.hcl
      workingDirectory: $(TF_WORKING_DIR)
      displayName: Clean Terraform cache

    - task: TerraformCLI@2
      displayName: Terraform Init
      inputs:
        command: 'init'
        workingDirectory: '$(TF_WORKING_DIR)'
        backendType: 'azurerm'
        backendServiceArm: 'payasyougo(c02db223-ae2a-4677-943f-e5864c5361a3)'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'tfstate-rg'
        backendAzureRmResourceGroupLocation: 'centralindia'
        backendAzureRmStorageAccountName: 'tfstatebankapp'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'
        allowTelemetryCollection: true


    - task: TerraformCLI@2
      displayName: Terraform Plan
      inputs:
        command: 'plan'
        workingDirectory: '$(TF_WORKING_DIR)'
        commandOptions: '-var subscription_id=$(subscription_id) -var tenant_id=$(tenant_id) -var client_id=$(client_id) -var client_secret=$(client_secret) -input=false -out=tfplan'
        allowTelemetryCollection: true
  


       

- stage: Cost
  dependsOn: Plan
  jobs:
  - job: cost
    steps:
    - task: InfracostSetup@2
      inputs:
        apiKey: $(INFRACOST_API_KEY)
        version: '0.10.x'
        currency: 'INR'
        
# ===============================
# STAGE 3: MANUAL APPROVAL
# ===============================
- stage: Approval
  dependsOn: Cost
  jobs:
  - job: approval
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: Review Terraform plan and approve infrastructure changes.

# ===============================
# STAGE 4: APPLY
# ===============================
- stage: Apply
  dependsOn: Approval
  jobs:
  - job: apply
    steps:
    - task: TerraformCLI@2
      displayName: Terraform Init
      inputs:
        command: 'init'
        workingDirectory: '$(TF_WORKING_DIR)'
        backendType: 'azurerm'
        backendServiceArm: 'payasyougo(c02db223-ae2a-4677-943f-e5864c5361a3)'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'tfstate-rg'
        backendAzureRmResourceGroupLocation: 'centralindia'
        backendAzureRmStorageAccountName: 'tfstatebankapp'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'
        allowTelemetryCollection: true

    - task: TerraformCLI@0
      displayName: Terraform Import RG
      inputs:
        command: import
        workingDirectory: $(TF_WORKING_DIR)
        resourceAddress: module.resource_group.azurerm_resource_group.rg
        resourceId: /subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/bankapp-dev-rg
        environmentServiceNameAzureRM: $(AZURE_SERVICE_CONNECTION)


    
    - task: TerraformCLI@2
      displayName: Terraform Apply
      inputs:
        command: 'apply'
        workingDirectory: '$(TF_WORKING_DIR)'
        commandOptions: '-var subscription_id=$(subscription_id) -var tenant_id=$(tenant_id) -var client_id=$(client_id) -var client_secret=$(client_secret)'
        allowTelemetryCollection: true