trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/auth/**

pool:
  name: azureagent

variables:
  IMAGE_NAME: auth
  ACR_NAME: bankdevacr
  ACR_LOGIN_SERVER: bankdevacr.azurecr.io
  IMAGE_TAG: $(Build.BuildId)

steps:
- checkout: self


- task: Docker@2
  inputs:
    containerRegistry: 'azure-container-registry'
    repository: '$(ACR_LOGIN_SERVER)/$(IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: 'services/auth'